ALTER TABLE clients
ADD COLUMN cep VARCHAR(10),
ADD COLUMN address VARCHAR(255),
ADD COLUMN address_number VARCHAR(20),
ADD COLUMN complement VARCHAR(100),
ADD COLUMN neighborhood VARCHAR(100),
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(2);
